# **Problem Statement: Linear Regression**

Load the housing_price.csv dataset to a DataFrame and perform the following tasks:The dataset contains only numeric data, and the median house value column is our target variable, so with the help of linear regression, build a model that can predict accurate house prices. Perform the below tasks and build a model:

1.Load the housing_price dataset  into DataFrame

2.Find the null value and drop then, If any

3.Split  data  into  two  DataFrames  x  and  y  based  on  dependent  and independent variables

4.Split x and y into 80% training set and 20% testing set. Set the random state to 10. Call the LinearRegression model, then fit the model  using train data

 5.Print the R2 value, coefficient, and intercept

 6.Compare actual and predicted values.

 7.Print the final summary


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import statsmodels.api as sm

1.Load the housing_price dataset  into DataFrame

In [ ]:
df=pd.read_csv("/content/housing_price.csv")
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                  15         5612            1283   
1    -114.47     34.40                  19         7650            1901   
2    -114.56     33.69                  17          720             174   
3    -114.57     33.64                  14         1501             337   
4    -114.57     33.57                  20         1454             326   

   population  households  median_income  median_house_value  
0        1015         472         1.4936               66900  
1        1129         463         1.8200               80100  
2         333         117         1.6509               85700  
3         515         226         3.1917               73400  
4         624         262         1.9250               65500

2.Find the null value and drop then, If any

In [ ]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

3.Split data into two DataFrames x and y based on dependent and independent variables

In [ ]:
x=df[['longitude','latitude','housing_median_age','total_rooms','total_bedrooms','population','households',	'median_income']].values
print("independent data:\n",x)
y=df['median_house_value'].values
print('dependent data:\n',y)

independent data:
 [[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]
dependent data:
 [ 66900  80100  85700 ... 103600  85800  94600]


4.Split x and y into 80% training set and 20% testing set. Set the random state to 10. Call the LinearRegression model, then fit the model using train data

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)
print('x_train and x_test data set:',x_train.shape,x_test.shape)
print('y_train and y_test data set:',y_train.shape,y_test.shape)

x_train and x_test data set: (13600, 8) (3400, 8)
y_train and y_test data set: (13600,) (3400,)


5.Print the R2 value, coefficient, and intercept

In [ ]:
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
r2=reg.score(x_test,y_test)
print('R2 value:',r2)

R2 value: 0.6484403017760421


In [ ]:
print('coefficient:\n',reg.coef_)
print("intercept:\n",reg.intercept_)

coefficient:
 [-4.34225673e+04 -4.34584915e+04  1.15417922e+03 -8.34683693e+00
  1.14234465e+02 -3.87425498e+01  5.04252279e+01  4.02554220e+04]
intercept:
 -3635200.010897606


6.Compare actual and predicted values.

In [ ]:
y_pred = reg.predict(x_test)
df1 = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
df1.head(10)


Actual      Predicted
0   96100   -8475.675202
1  500001  490876.394233
2  177200  112662.107990
3   55000  218093.753334
4  220800  207600.925885
5  158300  121540.170888
6   37900  180602.126583
7  115600  104694.108104
8  359700  310765.123759
9  203300  265864.990208

7.Print the final summary

In [ ]:
x2=sm.add_constant(x)
est=sm.OLS(y,x2)
est2=est.fit()
print(est2.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.641
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     3798.
Date:                Thu, 19 Oct 2023   Prob (F-statistic):               0.00
Time:                        08:51:30   Log-Likelihood:            -2.1365e+05
No. Observations:               17000   AIC:                         4.273e+05
Df Residuals:                   16991   BIC:                         4.274e+05
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.621e+06   6.92e+04    -52.312      0.0